services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - '5672:5672'
      - '15672:15672'
      
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - 'postgres_master_data:/postgres/data'
    ports:
      - '5432:5432'

volumes:
  postgres_master_data:
    driver: local