services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - '5672'

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - 'postgres_master_data:/postgres/data'
    ports:
      - '5432'

networks:
  default:
    name: nginx-proxy-manager_default
    external: true

volumes:
  postgres_master_data:
    driver: local