version: '3.8'
services:
  postgresql:
    container_name: postgresql
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - 'postgres_master_data:/postgres/data'
    ports:
      - '5432:5432'

networks:
  default:
    name: old-town-coffee
    external: true

volumes:
  postgres_master_data:
    driver: local
